# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './resources/ui_files/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(899, 543)
        MainWindow.setStyleSheet("background-color: rgb(44, 44, 44);")
        MainWindow.move(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LineTranslation = QtWidgets.QLineEdit(self.centralwidget)
        self.LineTranslation.setStyleSheet("color: rgb(236, 236, 236);")
        self.LineTranslation.setText("")
        self.LineTranslation.setObjectName("LineTranslation")
        self.gridLayout.addWidget(self.LineTranslation, 2, 2, 1, 1)
        self.BinsTranslate = QtWidgets.QPushButton(self.centralwidget)
        self.BinsTranslate.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 133, 255, 255), stop:1 rgba(255, 152, 255, 255));\n"
"color: rgb(0, 0, 0);")
        self.BinsTranslate.setObjectName("BinsTranslate")
        self.gridLayout.addWidget(self.BinsTranslate, 2, 0, 1, 1)
        self.Label1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Label1.setFont(font)
        self.Label1.setStyleSheet("color: rgb(236, 236, 236);")
        self.Label1.setObjectName("Label1")
        self.gridLayout.addWidget(self.Label1, 0, 2, 1, 1)
        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 133, 255, 255), stop:1 rgba(255, 152, 255, 255));\n"
"color: rgb(0, 0, 0);")
        self.Button1.setObjectName("Button1")
        self.gridLayout.addWidget(self.Button1, 0, 0, 1, 1)
        self.BinsWord = QtWidgets.QPushButton(self.centralwidget)
        self.BinsWord.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 133, 255, 255), stop:1 rgba(255, 152, 255, 255));\n"
"color: rgb(0, 0, 0);")
        self.BinsWord.setObjectName("BinsWord")
        self.gridLayout.addWidget(self.BinsWord, 1, 0, 1, 1)
        self.BinsTrancr = QtWidgets.QPushButton(self.centralwidget)
        self.BinsTrancr.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 133, 255, 255), stop:1 rgba(255, 152, 255, 255));\n"
"color: rgb(0, 0, 0);")
        self.BinsTrancr.setObjectName("BinsTrancr")
        self.gridLayout.addWidget(self.BinsTrancr, 3, 0, 1, 1)
        self.LineWord = QtWidgets.QLineEdit(self.centralwidget)
        self.LineWord.setStyleSheet("color: rgb(236, 236, 236);")
        self.LineWord.setText("")
        self.LineWord.setObjectName("LineWord")
        self.gridLayout.addWidget(self.LineWord, 1, 2, 1, 1)
        self.LineTranscr = QtWidgets.QLineEdit(self.centralwidget)
        self.LineTranscr.setStyleSheet("color: rgb(236, 236, 236);")
        self.LineTranscr.setText("")
        self.LineTranscr.setObjectName("LineTranscr")
        self.gridLayout.addWidget(self.LineTranscr, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.BShowTables = QtWidgets.QPushButton(self.centralwidget)
        self.BShowTables.setMaximumSize(QtCore.QSize(201, 28))
        self.BShowTables.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 133, 255, 255), stop:1 rgba(255, 152, 255, 255));\n"
"color: rgb(0, 0, 0);")
        self.BShowTables.setObjectName("BShowTables")
        self.verticalLayout.addWidget(self.BShowTables)
        self.BShowWords = QtWidgets.QPushButton(self.centralwidget)
        self.BShowWords.setMaximumSize(QtCore.QSize(201, 28))
        self.BShowWords.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 133, 255, 255), stop:1 rgba(255, 152, 255, 255));\n"
"color: rgb(0, 0, 0);")
        self.BShowWords.setObjectName("BShowWords")
        self.verticalLayout.addWidget(self.BShowWords)
        self.Button2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button2.setMaximumSize(QtCore.QSize(201, 28))
        self.Button2.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(122, 133, 255, 255), stop:1 rgba(255, 152, 255, 255));\n"
"color: rgb(0, 0, 0);")
        self.Button2.setObjectName("Button2")
        self.verticalLayout.addWidget(self.Button2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.OutputBlock = QtWidgets.QTextBrowser(self.centralwidget)
        self.OutputBlock.setEnabled(True)
        self.OutputBlock.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"color: rgb(255, 171, 230);")
        self.OutputBlock.setObjectName("OutputBlock")
        self.gridLayout_2.addWidget(self.OutputBlock, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 899, 23))
        self.menubar.setStyleSheet("color: rgb(236, 236, 236);")
        self.menubar.setObjectName("menubar")
        self.menuMath = QtWidgets.QMenu(self.menubar)
        self.menuMath.setStyleSheet("color: rgb(236, 236, 236);")
        self.menuMath.setObjectName("menuMath")
        self.menuDatabase = QtWidgets.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("color: rgb(236, 236, 236);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionWords = QtWidgets.QAction(MainWindow)
        self.actionWords.setObjectName("actionWords")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMath.addAction(self.actionExit)
        self.menuDatabase.addAction(self.actionWords)
        self.menubar.addAction(self.menuMath.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BinsTranslate.setText(_translate("MainWindow", "Ввести перевод"))
        self.Label1.setText(_translate("MainWindow", "Текст 1"))
        self.Button1.setText(_translate("MainWindow", "Кнопка 1"))
        self.BinsWord.setText(_translate("MainWindow", "Ввести слово"))
        self.BinsTrancr.setText(_translate("MainWindow", "Ввести транскрипцию"))
        self.BShowTables.setText(_translate("MainWindow", "Отобразить таблицы"))
        self.BShowWords.setText(_translate("MainWindow", "Отобразить слова"))
        self.Button2.setText(_translate("MainWindow", "Кнопка 2"))
        self.OutputBlock.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hello!</p></body></html>"))
        self.menuMath.setTitle(_translate("MainWindow", "Main"))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database"))
        self.actionWords.setText(_translate("MainWindow", "Words"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
