# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WordsListWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WList(object):
    def setupUi(self, WList):
        WList.setObjectName("WList")
        WList.resize(563, 361)
        WList.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(WList)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.WordsList = QtWidgets.QListWidget(WList)
        self.WordsList.setStyleSheet("background-color: rgb(165, 165, 165);\n"
"color: rgb(16, 16, 16);")
        self.WordsList.setObjectName("WordsList")
        self.horizontalLayout.addWidget(self.WordsList)

        self.retranslateUi(WList)
        QtCore.QMetaObject.connectSlotsByName(WList)

    def retranslateUi(self, WList):
        _translate = QtCore.QCoreApplication.translate
        WList.setWindowTitle(_translate("WList", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WList = QtWidgets.QWidget()
    ui = Ui_WList()
    ui.setupUi(WList)
    WList.show()
    sys.exit(app.exec_())
