# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './resources/ui_files/WordsTableWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WTable(object):
    def setupUi(self, WTable):
        WTable.setObjectName("WTable")
        WTable.resize(640, 480)
        WTable.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(WTable)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.WordsTable = QtWidgets.QTableWidget(WTable)
        self.WordsTable.setStyleSheet("background-color: rgb(43, 43, 43);\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgb(152, 152, 152);\n"
"alternate-background-color: rgb(152, 152, 152);\n"
"selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(138, 138, 138);\n"
"border-top-color: rgb(152, 152, 152);\n"
"gridline-color: rgb(152, 152, 152);\n"
"border-left-color: rgb(152, 152, 152);\n"
"border-right-color: rgb(152, 152, 152);\n"
"border-bottom-color: rgb(152, 152, 152);")
        self.WordsTable.setObjectName("WordsTable")
        self.WordsTable.setColumnCount(3)
        self.WordsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.WordsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.WordsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.WordsTable.setHorizontalHeaderItem(2, item)
        self.horizontalLayout.addWidget(self.WordsTable)

        self.retranslateUi(WTable)
        QtCore.QMetaObject.connectSlotsByName(WTable)

    def retranslateUi(self, WTable):
        _translate = QtCore.QCoreApplication.translate
        WTable.setWindowTitle(_translate("WTable", "Form"))
        item = self.WordsTable.horizontalHeaderItem(0)
        item.setText(_translate("WTable", "English"))
        item = self.WordsTable.horizontalHeaderItem(1)
        item.setText(_translate("WTable", "Перевод"))
        item = self.WordsTable.horizontalHeaderItem(2)
        item.setText(_translate("WTable", "Транскрипция"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WTable = QtWidgets.QWidget()
    ui = Ui_WTable()
    ui.setupUi(WTable)
    WTable.show()
    sys.exit(app.exec_())
